### ISSUE TITLE
Expected object of backend CPU but got backend CUDA for argument #2 'mask'

### ISSUE THREAD

**Issue by yuanjie-ai** [zasdfgbnm/TorchSnooper#5] opened 2019-06-03 02:19 UTC
![image](https://user-images.githubusercontent.com/20265321/58771868-105e4b00-85e9-11e9-8cfa-9372ec716727.png)

**Comment by zasdfgbnm** [comment] 2019-06-03 03:54
Hi @Jie-Yuan, could you scroll up your output and see if you get the output of PySnooper? It should be the red part in the below figure. If you see it, the this is the expected behavior, and the red message is the one you look at when using TorchSnooper to debug your code.
![image](https://user-images.githubusercontent.com/1032377/58774867-9a7ac500-8591-11e9-9c57-44f6ee9d2efd.png)

**Comment by zasdfgbnm** [comment] 2019-06-18 17:10
Hi @Jie-Yuan, I am closing this because I think this problem should be resolved. Let me know if the problem is still there.

**Closed as completed by zasdfgbnm** 2019-06-18 17:10 UTC
